---
- name: Pull docker image of Calculator
  hosts: localhost
  tasks:

    - name: Start docker service
      service:
        name: docker
        state: started
        
    - name: pull docker image
      shell: docker pull docker.io/riddhich/calculator:latest
      
    - name: running container
      shell: docker run -it -d --name Calculator riddhich/calculator
      
