---
- name: Pull Docker Image of Calculator
  hosts: localhost
  tasks:
    - name: Pull image
      docker_image:
        name: riddhich/calculator:latest
        source: pull
    - name: Start docker service
      service:
        name: docker
        state: started
    - name: Running container
      shell: /usr/local/bin/docker run -it -p 3000:3000 -d riddhich/calculator:latest
