---
- name: Pull Docker Image of Calculator
  hosts: localhost
  tasks:
    - name: Pull image
      docker_image:
        name: riddhich/calculator:latest
        source: pull
    
    - name: Running container
      shell: docker run -it -d --name Calculator riddhich/calculator
